apiVersion: v2
appVersion: "2.44.0"
description: "Dex - A Federated OpenID Connect Provider"
name: dex
version: 2.0.0
type: application
keywords:
  - dex
  - oidc
  - openid-connect
  - authentication
  - identity
home: https://dexidp.io/
icon: https://raw.githubusercontent.com/dexidp/dex/master/Documentation/logos/dex-horizontal-color.png
sources:
  - https://github.com/dexidp/dex
  - https://github.com/wowsel/dex-k8s-authenticator/tree/master/charts/dex
maintainers:
  - name: wowsel
    url: https://github.com/wowsel
